---
- name: install new feature
- hosts: serverb
- become: true
- gather_factor: no
- task:
  - name: install apache
    service:
    - name: apache2
    - state: present
  - name: install vim 
    service:
    - name: vim 
    - state: present
    